[WIP] Add new graphical representations to LanguageModel
FragileTech/language-competition pull request #8
Opened 2021-05-04 14:43 UTC by VicenteAR

Added new methods to represent the lattice (using holoviews). A few problems are in order: 
- method `_plot()` inside `run` is not properly called (plot is not returned)
- I can't get the desired layout. The idea is showing a composition 2 cols + 1 col (is the solution presented [here](https://github.com/holoviz/holoviews/issues/91)?)

Signed-off-by: VicenteAR <vicente.arjona@hotmail.com>

2021-05-06 16:56 UTC, VicenteAR commented
Fixed problems: 
- method `_plot()` inside `run` is not properly called (plot is not returned) => inside `_plot`, used __return display(...)__. This correctly shows the image. 
- I can't get the desired layout. The idea is showing a composition 2 cols + 1 col => used __panel.Column()__ and __panel.Row()__ combination.

2021-05-09 10:48 UTC, Guillemdb requested changes
Please remove the `matplotlib` imports before merging.

2021-05-09 10:48 UTC, Guillemdb commented on language_competition/models.py
>  import matplotlib as mpl
```suggestion

```

2021-05-09 10:48 UTC, Guillemdb commented on language_competition/models.py
>  import matplotlib.pyplot as plt
```suggestion
```

2021-05-09 10:49 UTC, Guillemdb commented on language_competition/models.py
```suggestion
from IPython.core.display import display

```

2021-05-10 08:32 UTC, VicenteAR commented
Fixed problems. Removed matplotlib libraries. Changed _repr_: moved from `matplotlib` to `holoviews`.

2021-05-10 08:32 UTC, merged